name: nightowl
description: A smart sleep tracker app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Notifications
  flutter_local_notifications: ^16.3.0

  # UI & Material icons
  cupertino_icons: ^1.0.2

  # State management
  provider: ^6.1.1

  # Local storage for theme/user data
  shared_preferences: ^2.2.2

  # Image picker for profile image (camera/gallery)
  image_picker: ^0.8.7+4

  # For date/time formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_sleep.png
    - assets/images/onboarding_alarm.png
    - assets/images/onboarding_analytics.png
    - assets/images/onboarding_wakeup.png
    - assets/images/dashboard_bg.png
    - assets/images/stars_overlay.png
    - assets/images/profile.jpg
    - assets/icons/moon.png
    - assets/icons/bed.png
    - assets/icons/alarm.png
    - assets/icons/chart.png
    - assets/icons/quote.png
    - assets/icons/download.png
    - assets/icons/zzz.png
    - assets/quotes/sleep_quotes.json
